name: start lioss
on:
#for test
#  issue_comment:
#    types: [created]
  schedule:
    - cron:  '0 */8 * * *'    
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}  
    - name: install and work
      run: |
        sudo apt-get update 
        sudo apt-get install p7zip-full unzip 
        (cd insec && sudo 7z x archive.7z -p${{ secrets.GIT_PASS }} -o/opt/)
        sudo apt-get install -y --fix-missing llvm clang libtool libtool-bin automake bison libglib2.0 git 
        sudo apt-get install -y git python3 python3-pandas python3-pip python3-setuptools
        sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
        sudo pip3 install wheel
        sudo -H pip3 install --ignore-installed PyYAML 
        sudo pip3 install pybadges 
        sudo python3 /opt/lioss.py  ${GITHUB_ACTOR} ${GITHUB_REPOSITORY} in/ /opt/ myProj/ myOut/ myCpus/ 280
